#!/bin/bash

# Copyright © 2011 Sebastian D. Tennant <sdt@sebyte.me>
#
# This file is part of swiQlisp — site-wide Quicklisp.
#
# swiQlisp is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# swiQlisp is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# swiQlisp.  If not, see <http://www.gnu.org/licenses/>

# Commentary:
#
#  This script (swiqlisp-uninstall) is the site-wide Quicklisp removal tool.
#
#  Use the script 'swiqlisp' to manage your site-wide Quicklisp installation on
#  a day-to-day basis.

#-----------------------------------------------------------------------------
source swiqlisp.rc
source swiqlisp-utils
check_help "Usage: ./swiqlisp-uninstall"
check_root_privileges
check_sysusr_home


#-----------------------------------------------------------------------------

if test -z "$(id -u $SYSUSR 2>/dev/null)"; then
    # no SYSUSR
    echo "SYSUSR ($SYSUSR) does not exist.

If you are certain that swiQlisp is installed, the most likely explanation is
that the value of SYSUSR has changed.  Please check ./swiqlisp.rc."
    exit 1;
fi

y-or-n-with-default-answer "Uninstall site-wide Quicklisp?  Confirm" n

if test "$ans" = "y" -o "$ans" = "Y"; then
    # uninstall by removing the system user and its home directory
    userdel --remove $SYSUSR
    sleep 1
    echo "Sytem user '$SYSUSR' with home directory '$SYSUSR_HOME' removed."
    echo "swiQlisp successfully uninstalled."
    # run swiqlisp-stanza
    source swiqlisp-stanza
else
    echo "Uninstallation operation aborted."
fi
