#!/bin/bash

# Copyright © 2011 Sebastian D. Tennant <sdt@sebyte.me>
#
# This file is part of swiQlisp — site-wide Quicklisp.
#
# swiQlisp is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# swiQlisp is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with
# swiQlisp.  If not, see <http://www.gnu.org/licenses/>

# Commentary:
#
#  This script (swiqlisp-uninstall) is the site-wide Quicklisp removal tool,
#  typically only used once.
#
#  Use the script swiqlisp to manage your site-wide Quicklisp installation on a
#  day-to-day basis.

source swiqlisp.rc
source swiqlisp-utils

if test $(id -u) -ne 0; then need_root; exit 1; fi

ask "Uninstall site-wide Quicklisp?  Confirm"

if test "$ans" = "y" -o "$ans" = "Y"; then
    if test -d $SWIQLISP_DIR; then
	rm -r $SWIQLISP_DIR
	sleep 1
	echo -e "Site-wide Quicklisp uninstalled."
    else
	echo -e "Directory $SWIQLISP_DIR not found.

If you're certain swiQlisp is installed, the most likely explanation is that the
value of SWIQLISP_DIR has been altered (in swiqlisp.rc)."
    fi
fi
